name: Atlas
version: 1.0
description: An interactive map in a web app.
author: Kyle Nanakdewa
website: https://plugins.akenland.com

api-version: 1.14
main: com.kylenanakdewa.atlasmap.AtlasPlugin

commands:
  atlas:
    description: View plugin information, and reload the plugin.
    permission: atlas.admin
    usage: /atlas <version/reload>